### ISSUE TITLE
Posible error de tipografía

### ISSUE THREAD

**Issue by Oxyrus** [TheScienceOfCode/Sibelius.Web#113]
Me parece que la línea

```
Sin embargo, no nos responsabilizamos de que la desactivación de los mismos impida el buen funcionamiento de la del sitio.
```

Debería ser

```
Sin embargo, no nos responsabilizamos de que la desactivación de los mismos impida el buen funcionamiento del sitio.
```
https://github.com/TheScienceOfCode/Sibelius.Web/blob/be17398d792a459210ae8bc5aecbd6d9ef3d6227/Sibelius.Web/Views/Home/Privacy.cshtml

Aunque no estoy completamente seguro si así lo deseaban escribir :question:

**Comment by dacanizares** [comment]
Gracias Oxyrus por reportarlo! Ya lo hemos corregido.
