### ISSUE TITLE
Botón de compartir en Facebook no aparece

### ISSUE THREAD

**Issue by Oxyrus** [TheScienceOfCode/Sibelius.Web#118]
![Imagen](http://i.imgur.com/V5WhTGx.png?1)

No se visualiza el share button de Facebook en la vista de show de los artículos.

**Comment by dacanizares** [comment]
Gracias Oxyrus por reportarlo. A veces hay mucho tráfico y FB tarda en responder. De todas formas hemos actualizado toda la sección. Mira a ver si mejoró, o sino nos indicas de que navegador estás para replicar el error.

¡Gracias!

**Comment by Oxyrus** [comment]
Ya aparece :smiley:
