### ISSUE TITLE
Advertencia de AdBlock aparece aún con este desactivado

### ISSUE THREAD

**Issue by Oxyrus** [TheScienceOfCode/Sibelius.Web#162]
![http://i.imgur.com/HN2XEeO.png](http://i.imgur.com/HN2XEeO.png)

**Comment by dacanizares** [comment]
Chequea que el antivirus no esté bloqueando los ads. Saludos!

**Comment by Oxyrus** [comment]
¿Antivirus? Que es eso, yo no uso xd
